### ISSUE TITLE
Error in git2r::lookup with devtools::release()

### ISSUE THREAD

**Issue by sachsmc** [hadley/devtools#1000]
I'm getting this error when running devtools::release()

    Error in git2r::lookup(r, git2r::branch_target(upstream)) : 
      error in evaluating the argument 'sha' in selecting a method for function 'lookup': Error in (function (classes, fdef, mtable)  : 
      unable to find an inherited method for function ‘branch_target’ for signature ‘"NULL"’

This is using the current CRAN versions of devtools and git2r, and R versions 3.2.3 on OSX 10.11.1. 

I've tried using the github versions of devtools and git2r, but I get the same error. 

dr_devtools() says that I look healthy. Any ideas what's going on?

**Comment by hadley** [comment]
I think this should all be resolved with the latest git2r release.

**Comment by iembry-USGS** [comment]
Hi Hadley, I am currently using devtools_1.9.1.9000 and git2r_0.13.1.9000 is loaded via a namespace. I used devtools to upgrade to both the development versions of devtools and git2r. Then, I terminated R and restarted R.

I am still getting the same  error message as sachsmc.

Can you reopen this issue?

Thank you.

Irucka Embry

**Comment by jennybc** [comment]
This happens when the package uses Git but not GitHub. You can reproduce it like so:

```r
library(git2r)
tpath <- tempfile("devtools")
create(tpath)
init(tpath)
release(tpath)
```

I am about to submit a fix.
