### ISSUE TITLE
1.13 - `install_bitbucket` fails with 'Error in value[[3L]](cond) : argument "quiet" is missing, with no default' 

### ISSUE THREAD

**Issue by r-cheologist** [hadley/devtools#1502]
PROMPT> devtools::install_bitbucket("graumannlabtools/readat")
    Error in value[[3L]](cond) : argument "quiet" is missing, with no default

    PROMPT> devtools::install_bitbucket("graumannlabtools/readat", quiet = FALSE)
    Error in value[[3L]](cond) : argument "quiet" is missing, with no default

    PROMPT> packageVersion("devtools")
    [1] ‘1.13.0’

    PROMPT> sessionInfo()
    R version 3.4.0 (2017-04-21)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Arch Linux
    
    Matrix products: default
    BLAS: /usr/lib/libblas.so.3.7.0
    LAPACK: /usr/lib/liblapack.so.3.7.0
    
    locale:
     [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8              LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
     [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
    [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] magrittr_1.5         BiocInstaller_1.24.0
    
    loaded via a namespace (and not attached):
     [1] httr_1.2.1      compiler_3.4.0  R6_2.2.0        tools_3.4.0     withr_1.0.2     curl_2.6        yaml_2.1.14     memoise_1.1.0   git2r_0.18.0   
    [10] digest_0.6.12   devtools_1.13.0

**Comment by jimhester** [comment]
This is now fixed in the 1.13.0 branch (https://github.com/hadley/devtools/tree/1.13.0), you can install it with `devtools::install_github("hadley/devtools@1.13.0")`

**Comment by r-cheologist** [comment]
Not true - fixed in your fork, but the following still's broken:

    PROMPT> devtools::install_github("hadley/devtools@1.13.0")
    Skipping install of 'devtools' from a github remote, the SHA1 (c071299c) has not changed since last install.
     Use `force = TRUE` to force installation
    
    PROMPT> packageVersion("devtools")
    [1] ‘1.13.0’

    PROMPT> devtools::install_bitbucket
    function (repo, username, ref = "master", subdir = NULL, quiet = FALSE, 
        auth_user = NULL, password = NULL, ...) 
    {
        remotes <- lapply(repo, bitbucket_remote, username = username, 
            ref = ref, subdir = subdir, auth_user = auth_user, password = password)
        install_remotes(remotes, ...)
    }
    <environment: namespace:devtools>

**Comment by jimhester** [comment]
Yes it is, https://github.com/hadley/devtools/blob/c071299c7014d01a846052bf1a05087c0726be5c/R/install-bitbucket.r#L29, you need to restart your R session.

**Comment by r-cheologist** [comment]
Even restarted the lxc-container this is running in and still get the error.
