### ISSUE TITLE
my_unzip should throw/display a meaningful error if `unzip` is empty

### ISSUE THREAD

**Issue by joncfoo** [hadley/devtools#1546]
I recently encountered the following issue:

    > devtools::install_github("rstudio/rsconnect")
    Downloading GitHub repo rstudio/rsconnect@master
    from URL https://api.github.com/repos/rstudio/rsconnect/zipball/master
    Installation failed: error in running command

This happened because R was configured without `R_UNZIPCMD` being set during build.

`my_unzip` should check if the `unzip` parameter is empty so it can either display a meaningful error message or use the internal unzip tool (from what I can gather from the code).

Workaround:  add `R_UNZIPCMD=/usr/bin/unzip` to `~/.Renviron`

**Comment by gaborcsardi** [comment]
Actually, anyone knows what the reason is for not using the internal unzip implementation?

**Comment by hadley** [comment]
I think it's a simple omission.

Should this get fixed in devtools or does it belong in remotes?

**Comment by gaborcsardi** [comment]
Sorry, for repeating this again, but can't we actually just use the internal unzip implementation instead of an external tool?

**Comment by hadley** [comment]
@gaborcsardi yes, we should be able to use the internal unzip command, I think.

**Comment by jimhester** [comment]
looks like the original issue looks like https://github.com/hadley/devtools/issues/540, but that still doesn't address just using the internal unzip unconditionally. From `?unzip`

> The default internal method is a minimal implementation,
     principally designed for Windows' users to be able to unpack
     Windows binary packages without external software.  It does not
     (for example) support Unicode filenames as introduced in ‘zip
     3.0’: for that use ‘unzip = "unzip"’ with ‘unzip 6.00’ or later.
     It does have some support for ‘bzip2’ compression and > 2GB zip
     files (but not >= 4GB files pre-compression contained in a zip
     file: like many builds of ‘unzip’ it may truncate these, in R's
     case with a warning if possible).

The no-unicode filenames could be an issue, the size limitations probably not for this use-case.

**Comment by hadley** [comment]
I feel like using unicode file names in an R package is likely to cause problems elsewhere.

**Comment by hadley** [comment]
The other approach would be to add unzip support to [zip](https://github.com/r-lib/zip) and then unconditionally use that

**Comment by gaborcsardi** [comment]
Either way is good. Adding `unzip` support to `zip` is easy. I would need to check if it supports unicode filenames.

Btw. the internal `untar` is an order of magnitude slower than the external one, but internal `unzip` seems to be fine.
